AWS_ACCESS_KEY_ID: AKIAJ5UNPQHPKES6XLBQ
AWS_SECRET_ACCESS_KEY: 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
development:
    SENDGRID_USERNAME:
    SENDGRID_PASSWORD:
    AWS_BUCKET:
production:
    AWS_BUCKET: 